var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/work/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1c9vk4y1rox1v._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0rgqgo7ku-q9v.js")
R.c("server/chunks/ssr/_0x4ben__3ak9q._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0272_7lx-l36l._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@edge-runtime_cookies_index_1kiz_an963mbg.js")
R.c("server/chunks/ssr/node_modules_next_dist_0janj0i6dqko7._.js")
R.c("server/chunks/ssr/_1i55amy83jemo._.js")
R.c("server/chunks/ssr/[root-of-the-server]__14n-nwufm4pwb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0y8_7di8cksm7._.js")
R.c("server/chunks/ssr/content_site_ts_1t22yibdzqq2h._.js")
R.c("server/chunks/ssr/app_not-found_tsx_1gi3i27gi6b-4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lhdi0ir6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0xky89qu.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892nagajq.js")
R.c("server/chunks/ssr/_next-internal_server_app_work_page_actions_03w9lt4ma6aoy.js")
R.m(42909)
module.exports=R.m(42909).exports
